import type { ColorPickerProps } from "../components/ColorPicker";

type Preset = {
    name: string;
    props: ColorPickerProps;
}

export const presets: { [key: string]: Preset } = {
    default: {
        name: "Default",
        props: {
            value: "#06B5EF",
            showContrast: true,
        }
    },
    hebrew: {
        name: "Clean Hebrew",
        props: {
            value: "#7B24D2",
            isRTL: true,
            showContrast: true,
            hexLabel: "הקס",
            rgbLabel: "ארג׳יבי",
            hslLabel: "האסאל",
            modeLabel: "מצב",
            contrastLabel: "ניגודיות",
            rLabel: "אדום",
            gLabel: "ירוק",
            bLabel: "כחול",
            hLabel: "גוון",
            sLabel: "רוויה",
            lLabel: "בהירות",
            floatingLabelFocusBorderColor: "#fff",
            floatingLabelActiveTextColor: "#7B24D2",
        }
    },
    italian: {
        name: "Strict Italian",
        props: {
            value: "#EF4006",
            enabledModes: ["hex", "rgb", "hsl"],
            saturationHeight: 210,
            saturationRadius: 0,
            saturationThumbRadius: 0,
            defaultFormat: "rgb",
            containerRadius: "0px",
            inputRadius: 0,
            previewRadius: 0,
            showContrast: true,
            hexLabel: "ESA",
            rgbLabel: "RGB",
            hslLabel: "TNL",
            modeLabel: "Modo",
            contrastLabel: "Rapporto di contrasto",
            rLabel: "Rosso",
            gLabel: "Verde",
            bLabel: "Blu",
            hLabel: "Ton",
            sLabel: "Sat",
            lLabel: "Lum",
            badgeBorderRadius: "0px" as any,
            contrastFormat: "value",
            hueTrackHeight: 14,
            hueTrackRadius: "0px" as any,
            hueTrackBorderColor: "#242424",
            hueThumbSize: 20,
            hueThumbRadius: "none" as any,
            modeDropdownWidth: "120px",
            dropdownMenuRadius: 0,
            contrastAreaTopMargin: "8px",
        }
    },
    lightMode: {
        name: "Light Version",
        props: {
            value: "#24EF23",
            enabledModes: ["hsl", "rgb"],
            defaultFormat: "hsl",
            containerBg: "#fafafa",
            containerBorderColor: "#e0e0e0",
            inputBg: "#fff",
            inputTextColor: "#111",
            floatingLabelTextColor: "#0059B8",
            floatingLabelActiveTextColor: "#0E82FF",
            floatingLabelFocusBorderColor: "#333333",
            floatingLabelBorderColor: "#333333",
            floatingLabelBorderWidth: 1,
            contrastLabel: "Contrast",
            rLabel: "Red",
            gLabel: "Green",
            bLabel: "Blue",
            hLabel: "Hue",
            sLabel: "Sat",
            lLabel: "Lum",
            showContrast: true,
            contrastValueColor: "#000",
            dropdownMenuBg: "#ffffff",
            dropdownMenuBorderColor: "#e0e0e0",
            dropdownMenuTextColor: "#333333",
            dropdownMenuActiveTextColor: "#000000",
            dropdownMenuHoverBg: "rgba(0,0,0,0.05)",
            dropdownMenuActiveBg: "rgba(0,0,0,0.10)",
            modeDropdownWidth: "96px",
            hueTrackHeight: 14,
            hueTrackBorderColor: "#333333",
            hueTrackBorderWidth: 1,
            hueThumbSize: 20,
            hueThumbBgDefault: "#333333",
            hueThumbBgHover: "#444444",
            hueThumbBgActive: "#555555",
            hueThumbBorderDefault: "#666666",
            hueThumbBorderHover: "#777777",
            hueThumbBorderActive: "#888888",
            saturationBorderColor: "#333",
            saturationBorderWidth: 1,
        }
    },
    cantonese: {
        name: "Festive Cantonese",
        props: {
            value: "#B406EF",
            enabledModes: ["rgb"],
            defaultFormat: "rgb",
            containerRadius: "24px",
            rgbLabel: "紅綠藍",
            rLabel: "紅",
            gLabel: "綠",
            bLabel: "藍",
            contrastLabel: "對比度",
            modeLabel: "模式",
            badgeBgPass: "rgba(255, 215, 0, 0.15)",
            badgeBgFail: "rgba(128, 128, 128, 0.15)",
            badgeBorderPass: "rgba(255, 215, 0, 0.5)",
            badgeBorderFail: "rgba(128, 128, 128, 0.5)",
            badgeTextPass: "#FFD700",
            badgeTextFail: "#808080",
            floatingLabelFocusBorderColor: "#FFD700",
            floatingLabelActiveTextColor: "#FF6B35",
            contrastFormat: "value",
        }
    },
    french: {
        name: "Base French",
        props: {
            value: "#4287f5",
            enabledModes: ["hex", "rgb"],
            containerRadius: "4px",
            hueTrackRadius: 4,
            hueThumbRadius: 4,
            inputRadius: 4,
            previewRadius: 4,
            saturationRadius: 4,
            saturationThumbRadius: 4,
            dropdownRadius: 4,
            dropdownMenuRadius: 4,
            badgeBorderRadius: "4px" as any,
            hexLabel: "HEX",
            rgbLabel: "RVB",
            modeLabel: "Mode",
            rLabel: "R",
            gLabel: "V",
            bLabel: "B",
            showContrast: false,
        }
    },
    japanese: {
        name: "Serene Japanese",
        props: {
            value: "#D6001C",
            containerBg: "#0A0E17",
            containerBorderColor: "#1F2832",
            containerRadius: "12px",
            containerPadding: "24px",
            enabledModes: ["hex", "rgb"],
            inputBg: "#151C26",
            inputBorderColor: "#2D3A4A",
            inputBorderWidth: 1,
            inputRadius: 8,
            inputTextColor: "#F0F4F8",
            inputErrorOutlineColor: "#8CE300",
            saturationHeight: 160,
            saturationRadius: 8,
            saturationBorderColor: "#2D3A4A",
            saturationBorderWidth: 1,
            saturationThumbWidth: 16,
            saturationThumbHeight: 16,
            saturationThumbRadius: 50,
            saturationThumbBorderStyle: "solid",
            saturationThumbBorderWidth: 1,
            saturationThumbBorderColor: "#F0F4F8",
            hueTrackHeight: 12,
            hueTrackRadius: "6px" as any,
            hueTrackBorderWidth: 1,
            hueTrackBorderColor: "#2D3A4A",
            hueThumbSize: 20,
            hueThumbRadius: "50%" as any,
            hueThumbBorderWidth: 1,
            hueThumbBgDefault: "#1A2333",
            hueThumbBgHover: "#25334A",
            hueThumbBgActive: "#334B62",
            hueThumbBorderDefault: "#F0F4F8",
            hueThumbBorderHover: "#FFFFFF",
            hueThumbBorderActive: "#FFFFFF",
            hexLabel: "十六進数",
            rgbLabel: "赤緑青",
            hslLabel: "色相・彩度・明度",
            modeLabel: "表示モード",
            contrastLabel: "コントラスト比",
            rLabel: "赤",
            gLabel: "緑",
            bLabel: "青",
            hLabel: "色相",
            sLabel: "彩度",
            lLabel: "明度",
            previewBgFallback: "#151C26",
            previewBorderColor: "#2D3A4A",
            previewBorderWidth: 1,
            previewRadius: 8,
            previewFontSize: 20,
            previewFontWeight: 500,
            previewTextColor: "#F0F4F8",
            floatingLabelBg: "#0A0E17",
            floatingLabelTextColor: "#8AA8C2",
            floatingLabelActiveTextColor: "#E13535",
            floatingLabelFocusBorderColor: "#E13535",
            floatingLabelRadius: 6,
            floatingLabelBorderColor: "#2D3A4A",
            floatingLabelBorderWidth: 1,
            dropdownHeight: 48,
            dropdownBg: "#151C26",
            dropdownBorderColor: "#2D3A4A",
            dropdownBorderWidth: 1,
            dropdownRadius: 8,
            dropdownTextColor: "#F0F4F8",
            dropdownFocusBorderColor: "#E13535",
            dropdownChevronColor: "#8AA8C2",
            dropdownMenuBg: "#0A0E17",
            dropdownMenuBorderColor: "#2D3A4A",
            dropdownMenuBorderWidth: 1,
            dropdownMenuRadius: 8,
            dropdownMenuTextColor: "#E0E8F0",
            dropdownMenuActiveTextColor: "#E13535",
            dropdownMenuHoverBg: "rgba(225,53,53,0.1)",
            dropdownMenuActiveBg: "rgba(225,53,53,0.15)",
            modeDropdownWidth: "120px",
            badgeBgPass: "rgba(227,53,53,0.18)",
            badgeBgFail: "rgba(70,80,90,0.25)",
            badgeBorderPass: "rgba(227,53,53,0.5)",
            badgeBorderFail: "rgba(70,80,90,0.5)",
            badgeTextPass: "#E13535",
            badgeTextFail: "#787878",
            badgeBorderRadius: "100px" as any,
            badgeFontWeight: 500,
        }
    }
};
